### ISSUE TITLE
missing post titles?

### ISSUE THREAD

**Issue by maelle** [LFOD/LFOD.github.io#12]
On https://livefreeordichotomize.com/posts/2018-01-22-a-set-seed-ggplot2-adventure/index.html I don't see a title but the source has one https://github.com/LFOD/LFOD.github.io/blob/8b1866714832f071b04dcdca063da8bde91556c1/posts/2018-01-22-a-set-seed-ggplot2-adventure/index.qmd#L2

**Comment by maelle** [comment]
This is Firefox on Ubuntu

![image](https://github.com/LFOD/LFOD.github.io/assets/8360597/c620d715-0d72-401f-9936-014561a2bab9)

**Comment by maelle** [comment]
I don't see the title on Chrome either.

**Comment by LucyMcGowan** [comment]
Thank you @maelle! I think it should be fixed in the most recent push but let me know if you still see the issue!
