### ISSUE TITLE
utterances not installed on new quarto blog?

### ISSUE THREAD

**Issue by danmackinlay** [LFOD/LFOD.github.io#4]
When commenting on https://livefreeordichotomize.com/posts/2022-09-19-migrating-from-hugo-to-quarto/ I get the following error:

> Error: utterances is not installed on `lfod/lfod.github.io`. If you own this repo, [**install the app**](https://github.com/apps/utterances). Read more about this change in [the PR](https://github.com/utterance/utterances/pull/25).

**Comment by LucyMcGowan** [comment]
I think this is fixed now, thank you!!
